server:
  port: 8090

spring:
  application:
    name: user-service

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      max-size: 10
      initial-size: 2
      max-idle-time: 30s

  codec:
    max-in-memory-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/security-prs1
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: BASIC

firebase:
  credentials: ${FIREBASE_CREDENTIALS}


logging:
  level:
    io.r2dbc: DEBUG
    pe.edu.vallegrande.user_service: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.server: DEBUG

